services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=receipts_app
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  price_scraper:
    build: 
      context: ./services/price_scraper
    volumes:
      - ./services:/app/services
    ports:
      - '8000:8000'
    command: uvicorn services.price_scraper.local_server:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: