services:
  db:
    image: postgres
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=receipts_app
      - POSTGRES_MAX_CONNECTIONS=20
    ports:
      - '5432:5432'
    networks:
      - receipts_app_network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
  price_scraper:
    build: 
      context: ./services/price_scraper
    hostname: price-scraper-service
    volumes:
      - ./services:/app/services
    ports:
      - '8000:8000'
    networks:
      - receipts_app_network
    command: uvicorn services.price_scraper.local_server:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: ./frontend
    hostname: frontend
    ports:
      - '3000:3000'
    # stdin_open: true
    # tty: true  # Keeps the container running for debugging
    depends_on:
      db:
        condition: service_healthy
    networks:
      - receipts_app_network
    volumes:
      - ./frontend:/app
      - ./services/price_scraper/tmp/screenshots:/app/public/screenshots
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm run db:deploy && npm run dev"
  nifi:
    image: apache/nifi:latest
    hostname: nifi1
    ports:
      - '8443:8443'
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_UI_COUNTRY=us
    networks:
      - receipts_app_network
    volumes:
      # - ./services/nifi/shared-directory:/opt/nifi/nifi-current/ls-target
      - ./services/nifi/data:/opt/nifi/nifi-current/data
      - ./services/nifi/conf:/opt/nifi/nifi-current/conf
      - ./services/nifi/logs:/opt/nifi/nifi-current/logs
      - ./services/nifi/drivers:/opt/nifi/nifi-current/drivers
    restart: always
    stdin_open: true
  nifi-registry:
    image: apache/nifi-registry:latest
    hostname: nifi-registry
    ports:
      - '18080:18080'
    networks:
      - receipts_app_network
    volumes:
      - ./services/nifi/registry/flow-storage:/opt/nifi-registry/nifi-registry-current/flow-storage
      - ./services/nifi/registry/database:/opt/nifi-registry/nifi-registry-current/database
    # stdin_open: true

networks:
  receipts_app_network:
    name: receipts_app_network
