import pandas as pd

REFERENCE_PRODUCTS = pd.DataFrame([
    {"id": 1, "name": "BBQ Sauce", "product_name": "BBQ Sauce"},
    {"id": 2, "name": "Beans", "product_name": "Canned black beans"},
    {"id": 3, "name": "Bouillon cubes", "product_name": "Bouillon Cubes"},
    {"id": 4, "name": "Candy", "product_name": "candy gummies"},
    {"id": 5, "name": "Cereal", "product_name": "Corn flakes cereal"},
    {"id": 6, "name": "Chia seeds", "product_name": "whole chia Seeds"},
    {"id": 7, "name": "Chips", "product_name": "Potato Chips"},
    {"id": 8, "name": "Chocolate", "product_name": "irresistible chocolate bar"},
    {"id": 9, "name": "Chocolate chips", "product_name": "baking chocolate chips"},
    {"id": 10, "name": "Cookies", "product_name": "Cookies"},
    {"id": 11, "name": "Cornstarch", "product_name": "cornstarch baking"},
    {"id": 12, "name": "Crackers", "product_name": "Crackers"},
    {"id": 13, "name": "Flour", "product_name": "all purpose white flour"},
    {"id": 14, "name": "Granola", "product_name": "Granola cereal"},
    {"id": 15, "name": "Granola bars", "product_name": "Granola Bars"},
    {"id": 16, "name": "Gum", "product_name": "Chewing Gum"},
    {"id": 17, "name": "Hot chocolate", "product_name": "Hot Chocolate"},
    {"id": 18, "name": "Jam", "product_name": "selection strawberry jam"},
    {"id": 19, "name": "Mac and cheese", "product_name": "cheddar mac and cheese"},
    {"id": 20, "name": "Milk", "product_name": "Milk"},
    {"id": 21, "name": "Misc", "product_name": "Bread loaf"},
    {"id": 22, "name": "Noodles", "product_name": "Instant Noodles"},
    {"id": 23, "name": "Oats", "product_name": "Instant Oats"},
    {"id": 24, "name": "Pasta", "product_name": "Pasta"},
    {"id": 25, "name": "Pasta sauce", "product_name": "Pasta Sauce"},
    {"id": 26, "name": "Peanut butter", "product_name": "Peanut Butter"},
    {"id": 27, "name": "Rice", "product_name": "long grain white rice"},
    {"id": 28, "name": "Salsa", "product_name": "Salsa"},
    {"id": 29, "name": "Spices", "product_name": "selection fine herbs"},
    {"id": 30, "name": "Spread", "product_name": "hazelnut chocolate spread"},
    {"id": 31, "name": "Vitamins", "product_name": "Multivitamins"},
    {"id": 32, "name": "Bread", "product_name": "White Bread"},
    {"id": 33, "name": "Hot dog buns", "product_name": "selection hot dog buns"},
    {"id": 35, "name": "Chicken nuggets", "product_name": "Chicken Nuggets"},
    {"id": 36, "name": "English muffins", "product_name": "English Muffins"},
    {"id": 37, "name": "Spring Rolls", "product_name": "Frozen Spring Rolls"},
    {"id": 38, "name": "Waffles", "product_name": "Waffles"},
    {"id": 39, "name": "Nuts", "product_name": "Mixed Nuts"},
    {"id": 40, "name": "Hot dogs saussages", "product_name": "Hot Dogs"},
    {"id": 41, "name": "Pizza crust", "product_name": "Pizza Crust"},
    {"id": 42, "name": "Marshmallows", "product_name": "Marshmallows"},
    {"id": 43, "name": "Cooking Oil", "product_name": "Vegetable Oil"},
    {"id": 44, "name": "Sugar", "product_name": "Granulated Sugar"},
    {"id": 45, "name": "Baked good", "product_name": "carrot muffins"},
    {"id": 47, "name": "Salad dressing", "product_name": "Salad Dressing"},
    {"id": 48, "name": "Dates", "product_name": "Dates"},
    {"id": 49, "name": "Bagels", "product_name": "Bagels"},
    {"id": 50, "name": "Soup", "product_name": "Canned Soup"},
    {"id": 51, "name": "Prepared meal (mac and cheese)", "product_name": "Frozen meal"},
    {"id": 52, "name": "Cupcake", "product_name": "Cupcakes"},
    {"id": 53, "name": "Pie", "product_name": "Frozen Pie"},
    {"id": 54, "name": "Seasoned meat", "product_name": "tournedos"},
    {"id": 55, "name": "Tortillas wraps", "product_name": "flour tortillas"},
    {"id": 56, "name": "Poutine", "product_name": "Frozen Poutine"},
    {"id": 57, "name": "Ice cream", "product_name": "Ice Cream"},
    {"id": 58, "name": "Cold cuts deli meats", "product_name": "Cold Cuts"},
    {"id": 59, "name": "Cake", "product_name": "Cake"},
    {"id": 60, "name": "Frozen Pizza", "product_name": "Frozen Pizza"},
    {"id": 61, "name": "Tofu tempeh", "product_name": "Tofu"},
    {"id": 62, "name": "Pogos", "product_name": "Pogos"},
    {"id": 108, "name": "Iron supplement", "product_name": "Iron Supplements"},
    {"id": 109, "name": "Quinoa", "product_name": "Quinoa"}
])